# fly.toml app configuration file generated for engine-service-thrumming-meadow-7066 on 2025-10-08T00:54:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'engine-service-thrumming-meadow-7066'
primary_region = 'fra'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
