name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Claude Code
        run: curl https://claude.sh | bash

      - name: Run Claude Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
        run: |
          claude -p --system-prompt "$(cat .github/claude-system-prompt.txt)" << 'EOF' > /tmp/review.txt
          Review this PR and output ONLY this format with no markdown:
          
          GUIDELINE VIOLATIONS
          - file:line-range - Issue
          
          POTENTIAL BUGS
          - file:line-range - Issue
          EOF
          
          gh pr comment $PR_NUMBER --body "$(cat /tmp/review.txt)" || \
          gh issue comment $PR_NUMBER --body "$(cat /tmp/review.txt)"