name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: false
    # Original condition (disabled):
    # (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
    # (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
    # (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
    # (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Read system prompt
        id: prompt
        run: |
          {
            echo 'content<<EOF'
            cat .github/claude-system-prompt.txt
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: --system-prompt "${{ steps.prompt.outputs.content }}"