name: Migrate Review Apps Database

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "migrate" to confirm you want to run migrations on review apps database'
        required: true
        default: ''

jobs:
  migrate-review-apps-database:
    name: Run Database Migrations on Review Apps
    runs-on: ubuntu-latest

    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "migrate" ]; then
            echo "❌ Migration cancelled. You must type 'migrate' to confirm."
            exit 1
          fi
          echo "✅ Confirmation validated. Proceeding with migration."

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        run: npm run db:migrate
        env:
          DB_POSTGRES_URL: ${{ secrets.POSTGRES_URL_REVIEW_APPS }}

      - name: Migration completed
        run: echo "✅ Database migrations completed successfully for review apps database"
